name: Cargo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: read
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "never"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: test (dev)
        run: cargo test --lib --all-features
      - name: test (release)
        run: cargo test --lib --all-features --release
  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - name: clippy
        run: cargo clippy --no-deps
  rustdoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: rustdoc
        run: cargo doc --no-deps
